Handle nil options when resolving config conflicts
* Avoid `NoMethodError: undefined method `[]' for nil:NilClass`
* Skip missing config options due to bad formatting